development:
  adapter: postgresql
  encoding: unicode
  database: design_exchange_development

test:
  adapter: postgresql
  encoding: unicode
  database: design_exchange_test

production:
  adapter: postgresql
  encoding: unicode
  database: design_exchange_production
